### ISSUE TITLE
Encoding::UndefinedConversionError from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by mswiszcz** [karafka/sidekiq-backend#24] opened 2019-02-06 12:53 UTC
Hey.

We are having problems with message encoding. Seems that ruby-kafka is returning message value in ASCII-8BIT, and while it is not a problem for JSON.parse, it seems that sidekiq cannot really handle it. We have introduced interchanger as a solution which basically does force_encoding on message value

```ruby
# frozen_string_literal: true

module Interchangers
  class CustomInterchanger < Karafka::Interchanger
    class << self
      def encode(params_batch)
        params_batch.to_a.tap do |batch|
          batch.each do |params|
            params['value'].force_encoding(Encoding.default_internal)
          end
        end
      end
    end
  end
end
```

But maybe there might be a better solution that might be built into karafka or sidekiq-backend?

Here is full stacktrace of the issue

```
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb line 38 in encode
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb line 38 in to_json
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb line 38 in to_json
/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb line 224 in generate
/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb line 224 in generate
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq.rb line 182 in dump_json
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 201 in block in atomic_push
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 199 in map
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 199 in atomic_push
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 184 in block (2 levels) in raw_push
/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb line 2362 in block in multi
/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb line 45 in block in synchronize
/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb line 226 in mon_synchronize
/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb line 45 in synchronize
/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb line 2355 in multi
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 183 in block in raw_push
/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb line 65 in block (2 levels) in with
/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb line 64 in handle_interrupt
/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb line 64 in block in with
/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb line 61 in handle_interrupt
/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb line 61 in with
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 182 in raw_push
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb line 74 in push
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/worker.rb line 143 in client_push
/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/worker.rb line 87 in perform_async
/shared/bundle/ruby/2.5.0/gems/karafka-sidekiq-backend-1.2.0/lib/karafka/backends/sidekiq.rb line 17 in block in process
/shared/bundle/ruby/2.5.0/gems/dry-monitor-0.1.2/lib/dry/monitor/notifications.rb line 8 in measure
/shared/bundle/ruby/2.5.0/gems/dry-monitor-0.1.2/lib/dry/monitor/notifications.rb line 42 in instrument
/shared/bundle/ruby/2.5.0/gems/karafka-sidekiq-backend-1.2.0/lib/karafka/backends/sidekiq.rb line 16 in process
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/base_consumer.rb line 46 in call
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/delegator.rb line 38 in block (2 levels) in call
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/delegator.rb line 36 in each
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/delegator.rb line 36 in block in call
/shared/bundle/ruby/2.5.0/gems/dry-monitor-0.1.2/lib/dry/monitor/notifications.rb line 8 in measure
/shared/bundle/ruby/2.5.0/gems/dry-monitor-0.1.2/lib/dry/monitor/notifications.rb line 42 in instrument
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/delegator.rb line 24 in call
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/listener.rb line 42 in block in fetch_loop
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/client.rb line 32 in block in fetch_loop
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 224 in block (4 levels) in each_message
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb line 168 in block in instrument
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb line 23 in instrument
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb line 168 in instrument
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/instrumenter.rb line 21 in instrument
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/instrumenter.rb line 35 in instrument
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 222 in block (3 levels) in each_message
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 207 in each
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 207 in block (2 levels) in each_message
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 206 in each
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 206 in block in each_message
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/patches/ruby_kafka.rb line 27 in block in consumer_loop
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 387 in block in consumer_loop
/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb line 170 in instrument
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/instrumenter.rb line 21 in instrument
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/instrumenter.rb line 35 in instrument
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 386 in consumer_loop
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/patches/ruby_kafka.rb line 15 in consumer_loop
/shared/bundle/ruby/2.5.0/gems/ruby-kafka-0.6.8/lib/kafka/consumer.rb line 203 in each_message
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/client.rb line 32 in fetch_loop
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/listener.rb line 39 in fetch_loop
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/connection/listener.rb line 23 in call
/shared/bundle/ruby/2.5.0/gems/karafka-1.2.4/lib/karafka/fetcher.rb line 19 in block (2 levels) in call 
```

**Comment by mensfeld** [comment] 2019-02-06 12:54
https://github.com/karafka/sidekiq-backend#interchangers :)

**Comment by mswiszcz** [comment] 2019-02-06 12:59
Hey @mensfeld  thanks for quick response. That's basically what we did (that's where encode method is comming from), but I thought that it might be a common issue and it may be worth to implement a built-in solution. What do you think?

**Comment by mensfeld** [comment] 2019-02-06 13:02
@mswiszcz anytime. I don't want my answer to sound rude (you know how it is not a f2f conversation :D) but: 

>  I thought that it might be a common issue and it may be worth to implement a built-in solution

There is one. It's called interchangers ;)

I don't want to use a custom Sidekiq interchanger by default as the penalty is performance.

But maybe you have an idea on how to increase the visibility of the problem and the solution in the wiki?

**Comment by mswiszcz** [comment] 2019-02-06 13:06
Hmm, I was thinking that maybe we could actually force_encoding of the message value to Encoding.default_internal in karafka itself when it reads messages from ruby-kafka. That could be one option to fix this issue.

Regarding making it more visible, maybe it's worth to just add a wiki page and an link in README.md with information about this and the code sample I've given above?

**Comment by mensfeld** [comment] 2019-02-06 13:20
>  maybe we could actually force_encoding of the message value to Encoding.default_internal in karafka itself

Karafka needs to remain encoding agnostic. I don't want to impose any encoding as people may send binary data using Karafka as well. It's not a common case but it did happen couple of times.

> Regarding making it more visible, maybe it's worth to just add a wiki page and an link in README.md

Hmm but isn't that exactly what is described in the sidekiq backend readme?

> with information about this and the code sample I've given above?

That is a good idea and I will do that.

Please close the issue if you consider my answer sufficient and good luck using Karafka ecosystem!

**Comment by mswiszcz** [comment] 2019-02-06 13:32
Maybe an option would be to give a configuration option either to karafka or sidekiq backend like `config.force_message_encoding = Encoding::UTF_8`?

Yeah the second sentence was about this exact encoding problem - so it would be easy to find the solution by googling the problem, but it will be as well with this issue ticket here.

**Comment by mensfeld** [comment] 2019-02-06 13:33
But this actually doesn't make any sense to add to Karafka (sorry).

It would have to be an option used by the default parser not karafka itself and since parsers are already configurable, we would have a config setting for only the default parser.

**Comment by mswiszcz** [comment] 2019-02-06 13:40
Hmm, maybe you are right. For me using this interchanger to do encoding change just feels like doing a hack for something that should be handled by all the layers that are here. I would expect that in case I am using polish characters and my default_encoding in system is UTF_8 it works out of the box. Maybe it should be a case in ruby-kafka then? Not sure, I am still quite fresh with all this kafka-related stuff.

Either way thanks for quick discussion and making the issue more visible for others. Cheers :v:

**Comment by mensfeld** [comment] 2019-02-06 13:43
> Hmm, maybe you are right. For me using this interchanger to do encoding change just feels like doing a hack for something that should be handled by all the layers that are here.

Well that depends what and where you want to do with your data.

>  I would expect that in case I am using polish characters and my default_encoding in system is UTF_8 it works out of the box.

That depends on the way data was sent. `ruby-kafka` is also agnostic. If I were you, I would check the system that sends the messages to Kafka.

One thing you could do, that could seem more in place, is to use a custom parser that would force the encoding for you.

**Comment by mswiszcz** [comment] 2019-02-06 13:46
We are using waterdrop to send this stuff and before the message is send everything is in UTF-8. 

I've as well tested by creating a message using kafka CLI tools and reading those in ruby with ruby-kafka, and encoding of those messages was ASCII-8BIT.

Could you explain a little more about those parsers or link to how to create one?

**Comment by mensfeld** [comment] 2019-02-06 13:47
> We are using waterdrop to send this stuff and before the message is send everything is in UTF-8.

Hmmm. Is there a chance you could create an example app to explore that? If that's the case, it sounds a bit like a bug in `ruby-kafka` (that I could fix).

> Could you explain a little more about those parsers or link to how to create one?

https://github.com/karafka/karafka/wiki/Parsers :)

**Comment by mswiszcz** [comment] 2019-02-06 13:52
Thanks. I'll try to debug this with small example app and reach back later with it

**Comment by mensfeld** [comment] 2019-02-06 13:53
Thank you. If I'm able to reproduce it, I will be able to fix it :) Please open a separate issue in the main karafka repo for that one!

**Closed by mensfeld** 2019-02-06 13:53 UTC
Labels: question

**Comment by mswiszcz** [comment] 2019-02-06 14:21
In before I create separate issue for this, I am attaching 3 scripts I've quickly made to test it out.

[Download scripts - Archive.zip](https://github.com/karafka/sidekiq-backend/files/2836654/Archive.zip)

0. You need kafka and water_drop gems installed globally.
1. Create kafka topic

```sh
/usr/local/bin/kafka-topics --create --topic testejro --zookeeper localhost:2181 --partitions 1 --replication-factor 1
```

2. Run consumer `ruby consumer.rb`
3. Run producer.rb (this one uses waterdrop to send messages) `ruby producer.rb`
4. Run producer_kafka.rb (this one doesnt use waterdrop) `ruby producer_kafka.rb`

All messages are being send in UTF-8 and consumer gets those in ASCII-8BIT.

**Comment by mensfeld** [comment] 2019-02-06 14:22
I was able to reproduce. Looking into this. Thank you!

**Comment by mensfeld** [comment] 2019-02-06 15:07
Ok I got my answer. Look here: https://github.com/mperham/sidekiq/issues/3638 and https://github.com/mperham/sidekiq/issues/197

`ASCII-8BIT` is a binary. And this is expected due to Karafka's feature that defers the deserialization (parsing) of the payload into the sidekiq job as well if not used earlier within callback chain.

That means, that non ascii data won't be serialized to Sidekiq.

Solutions could be two:

  - 1. Deserialize data always in Karafka (slightly bad, deserializing can be expensive)
  - 2. Force encoding before enqueuing (really bad, we shouldn't be changing the binary encoding to something else)
  - 3. Make the issue more visible via docs

**Comment by mswiszcz** [comment] 2019-02-06 16:03
I. I agree it may be expensive. I think it should be done like it's done so deserializing here is not an option. 
II. The thing is that in case sidekiq would use MultiJson or Oj ([here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L183)) for serialization, it would change encoding automatically, is it really that bad? In the end, JSON.generate will also create string with default_encoding (UTF-8 in my case) but cannot really handle ASCII_8BIT characters

```ruby
irb(main):007:0> a = "test".encode(Encoding::ASCII_8BIT)
=> "test"
irb(main):008:0> a.encoding
=> #<Encoding:ASCII-8BIT>
irb(main):009:0> JSON.generate({ z: a }).encoding
=> #<Encoding:UTF-8>
```

**Comment by mensfeld** [comment] 2019-02-06 16:04
It is for raw binary data (stream of bytes).

**Comment by mswiszcz** [comment] 2019-02-06 16:06
So the only real option would actually be to change this method in sidekiq I've mentioned to utilize MultiJson or Oj :/

**Comment by mensfeld** [comment] 2019-02-06 16:08
or deserialize before insert. You can achieve that by running following code from your consumer:

```ruby
class BlablablaCOnsumer < Whateva
  include Karafka::Consumers::Callbacks

  after_fetch { params_batch.parsed }
end
```

**Comment by mswiszcz** [comment] 2019-02-06 16:14
That's kinda similar to what I did in the first place with interchanger. Thanks for help :) For now I'll stick with the interchanger I've mentioned, but I see it might cause issues when we will start to send images and unicode characters in the same messages.

**Comment by mensfeld** [comment] 2019-02-06 16:15
You can always use a binary interchanger from the example. It should be safe.
